#!/bin/bash
# setup.sh — iMessage Pet Bot 원클릭 설치
# -----------------------------------------------------------------
set -e
cd "$(dirname "$0")"

echo ""
echo "  🦀 iMessage Pet Bot Setup"
echo "  ─────────────────────────"
echo ""

# ── 1. Python 확인 ──
if ! command -v python3 &>/dev/null; then
    echo "❌ python3이 설치되어 있지 않습니다."
    echo "   brew install python3"
    exit 1
fi
echo "✓ Python3: $(python3 --version 2>&1)"

# ── 2. 의존성 설치 ──
echo ""
echo "📦 의존성 설치 중..."
pip3 install -q -r requirements.txt 2>&1 | grep -v "already satisfied" || true
echo "✓ 의존성 설치 완료"

# ── 3. 메시징 모드 선택 ──
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  📱 메시징 모드 선택"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1) 별도 번호/이메일 (추천)"
echo "     Mac에 연결된 다른 번호 또는 iMessage 이메일을 사용합니다."
echo "     에코 문제가 없고 대화가 깔끔합니다."
echo ""
echo "  2) 같은 번호 사용"
echo "     현재 사용 중인 번호로 자신에게 메시지를 보냅니다."
echo "     에코 방지가 자동으로 활성화됩니다."
echo ""
read -p "선택 (1/2) [1]: " MSG_MODE_CHOICE
MSG_MODE_CHOICE=${MSG_MODE_CHOICE:-1}

if [[ "$MSG_MODE_CHOICE" == "2" ]]; then
    MESSAGING_MODE="same"
    echo ""
    echo "✓ 같은 번호 모드 — 에코 방지가 자동으로 활성화됩니다."
else
    MESSAGING_MODE="separate"
    echo ""
    echo "✓ 별도 번호 모드"
    echo "  💡 Mac의 메시지 앱 → 설정 → iMessage에서"
    echo "     '새 대화 시작 시 사용할 주소'를 별도 이메일로 설정하세요."
fi

# ── 4. 전화번호 입력 ──
echo ""
if [ -f .env ] && grep -q "RECIPIENT_PHONE=+" .env 2>/dev/null; then
    CURRENT=$(grep "RECIPIENT_PHONE=" .env | cut -d= -f2)
    echo "현재 설정된 번호: $CURRENT"
    read -p "변경하시겠습니까? (y/N): " CHANGE
    if [[ "$CHANGE" != "y" && "$CHANGE" != "Y" ]]; then
        PHONE="$CURRENT"
    fi
fi

if [ -z "$PHONE" ]; then
    if [[ "$MESSAGING_MODE" == "same" ]]; then
        echo "현재 사용 중인 iMessage 전화번호를 입력하세요."
    else
        echo "펫 메시지를 받을 전화번호를 입력하세요."
    fi
    echo "형식: +821012345678 (국가코드 포함)"
    echo ""
    while true; do
        read -p "📱 전화번호: " PHONE
        # +숫자 10~15자리 검증
        if [[ "$PHONE" =~ ^\+[0-9]{10,15}$ ]]; then
            break
        else
            echo "⚠️  올바른 형식이 아닙니다. 예: +821012345678"
        fi
    done
fi

# ── 4. DRY_RUN — 첫 설치는 항상 테스트 모드로 시작 ──
DRY_RUN="true"

# ── 5. Permission Request 설정 ──
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🔐 Permission Request 설정"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Claude Code가 위험한 명령어(rm, git push 등)를 실행하려 할 때"
echo "  iMessage로 승인 요청을 보내는 기능입니다."
echo ""
echo "  1) OFF      — Permission 요청 비활성화 (상태 알림만)"
echo "  2) 타임아웃  — N초 내 미응답 시 자동 허용 또는 자동 거부"
echo "  3) 무제한    — 답장할 때까지 대기 (자리 비움에 최적)"
echo ""
read -p "선택 (1/2/3) [1]: " PERM_CHOICE
PERM_CHOICE=${PERM_CHOICE:-1}

PERM_ENABLED="false"
PERM_TIMEOUT=45
PERM_DEFAULT="allow"

if [[ "$PERM_CHOICE" == "2" ]]; then
    PERM_ENABLED="true"
    read -p "타임아웃 시간 (초) [45]: " PERM_TIMEOUT_INPUT
    PERM_TIMEOUT=${PERM_TIMEOUT_INPUT:-45}

    echo ""
    echo "  타임아웃 시 기본 동작:"
    echo "  a) 자동 허용 — 작업 흐름이 끊기지 않음 (기본값)"
    echo "  b) 자동 거부 — 안전 우선, 직접 확인해야 진행"
    read -p "선택 (a/b) [a]: " DEFAULT_CHOICE
    if [[ "$DEFAULT_CHOICE" == "b" || "$DEFAULT_CHOICE" == "B" ]]; then
        PERM_DEFAULT="deny"
    fi
elif [[ "$PERM_CHOICE" == "3" ]]; then
    PERM_ENABLED="true"
    PERM_TIMEOUT=0
    echo ""
    echo "  무제한 대기 모드: 답장할 때까지 Claude Code가 일시 정지됩니다."
    echo "  ⚠️  답장을 잊으면 Claude Code가 멈춘 상태로 유지됩니다."
    echo ""
    echo "  만약 응답을 잊었을 때의 기본 동작:"
    echo "  a) 자동 허용"
    echo "  b) 자동 거부"
    read -p "선택 (a/b) [b]: " DEFAULT_CHOICE
    if [[ "$DEFAULT_CHOICE" == "a" || "$DEFAULT_CHOICE" == "A" ]]; then
        PERM_DEFAULT="allow"
    else
        PERM_DEFAULT="deny"
    fi
fi

echo ""
if [[ "$PERM_ENABLED" == "true" ]]; then
    TIMEOUT_STR="무제한"
    [[ "$PERM_TIMEOUT" != "0" ]] && TIMEOUT_STR="${PERM_TIMEOUT}초"
    echo "✓ Permission: ON (타임아웃=${TIMEOUT_STR}, 기본=${PERM_DEFAULT})"
else
    echo "✓ Permission: OFF"
fi

# ── 6. .env 생성 ──
cat > .env <<EOF
# iMessage Pet Bot Configuration (auto-generated by setup.sh)

RECIPIENT_PHONE=$PHONE
MESSAGING_MODE=$MESSAGING_MODE
SERVER_PORT=23456

LOG_LEVEL=INFO
LOG_DIR=./logs

DAILY_MESSAGE_LIMIT=100
QUIET_HOURS_START=0
QUIET_HOURS_END=8

POLLING_INTERVAL=2
DRY_RUN=$DRY_RUN

# Permission Request
PERMISSION_ENABLED=$PERM_ENABLED
PERMISSION_TIMEOUT=$PERM_TIMEOUT
PERMISSION_DEFAULT=$PERM_DEFAULT
EOF
echo ""
echo "✓ .env 생성 완료"

# ── 7. GIF 에셋 생성 ──
if [ ! -f assets/gif/idle.gif ]; then
    echo ""
    echo "🎨 GIF 에셋 생성 중..."
    python3 assets/generate_gifs.py
else
    echo "✓ GIF 에셋 이미 존재"
fi

# ── 8. Claude Code Hook 등록 ──
echo ""
read -p "Claude Code hook을 등록할까요? (Y/n): " HOOK
if [[ "$HOOK" != "n" && "$HOOK" != "N" ]]; then
    python3 hooks/install.py
else
    echo "⏭️  Hook 등록 건너뜀 (나중에 python3 hooks/install.py 로 등록 가능)"
fi

# ── 9. macOS 권한 안내 ──
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ⚠️  macOS 권한 확인 (최초 1회)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. Full Disk Access (chat.db 읽기용)"
echo "     시스템 설정 → 개인정보 보호 및 보안 → 전체 디스크 접근 권한"
echo "     → 터미널(Terminal) 또는 사용 중인 터미널 앱 추가"
echo ""
echo "  2. Automation (메시지 발송용)"
echo "     처음 실행 시 '메시지 앱 제어' 허용 팝업이 뜹니다."
echo ""

# ── 10. DRY_RUN 자동 테스트 ──
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🧪 DRY_RUN 연결 테스트"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  실제 iMessage를 보내지 않고 서버 연결을 테스트합니다..."
echo ""

LOG_FILE="/tmp/pet-dryrun-test.log"
rm -f "$LOG_FILE"

# 봇 백그라운드 시작
python3 main.py > "$LOG_FILE" 2>&1 &
BOT_PID=$!

# 서버 기동 대기 (최대 5초)
SERVER_OK=0
for i in {1..10}; do
    sleep 0.5
    if curl -s "http://127.0.0.1:23456/state" --max-time 1 -o /dev/null 2>/dev/null; then
        SERVER_OK=1
        break
    fi
done

if [[ "$SERVER_OK" == "1" ]]; then
    echo "  ✓ HTTP 서버 시작됨 (port 23456)"

    # SessionStart 이벤트 전송
    RESP=$(curl -s -X POST "http://127.0.0.1:23456/state" \
        -H "Content-Type: application/json" \
        -d '{"event":"SessionStart","payload":{}}' \
        --max-time 3 2>/dev/null)

    sleep 0.5

    # PreToolUse 이벤트 전송
    curl -s -X POST "http://127.0.0.1:23456/state" \
        -H "Content-Type: application/json" \
        -d '{"event":"PreToolUse","payload":{}}' \
        --max-time 3 > /dev/null 2>/dev/null

    sleep 0.5

    if echo "$RESP" | grep -q '"ok"'; then
        echo "  ✓ 이벤트 수신 및 상태 전환 정상"
    else
        echo "  ⚠️  이벤트 응답 이상: $RESP"
    fi

    echo ""
    echo "  📋 봇 로그 (마지막 5줄):"
    echo "  ─────────────────────────────────────────"
    tail -5 "$LOG_FILE" 2>/dev/null | sed 's/^/     /'
    echo "  ─────────────────────────────────────────"
    echo ""
    echo "  ✅ DRY_RUN 테스트 완료 — 로그에만 기록되었습니다."
else
    echo "  ⚠️  서버가 응답하지 않습니다."
    echo "  로그:"
    cat "$LOG_FILE" 2>/dev/null | tail -5 | sed 's/^/     /'
    echo ""
    echo "  설치 후 수동으로 ./start.sh 를 실행해 확인하세요."
fi

# 테스트 봇 종료
kill "$BOT_PID" 2>/dev/null
wait "$BOT_PID" 2>/dev/null

# ── 11. 실제 발송 전환 선택 ──
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  📱 실제 iMessage 발송 전환"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  현재: DRY_RUN=true (로그 전용)"
echo ""
echo "  실제 발송으로 전환하면 Claude Code 작업 시"
echo "  ${PHONE} 번호로 GIF + 메시지가 전송됩니다."
echo ""
read -p "실제 iMessage 발송 모드로 전환할까요? (y/N): " SWITCH_LIVE

if [[ "$SWITCH_LIVE" == "y" || "$SWITCH_LIVE" == "Y" ]]; then
    sed -i '' 's/^DRY_RUN=true/DRY_RUN=false/' .env
    DRY_RUN="false"
    echo ""
    echo "  ✓ DRY_RUN=false — 실제 iMessage 발송 모드로 전환되었습니다."
else
    echo ""
    echo "  ✓ DRY_RUN=true 유지 — 로그만 기록됩니다."
    echo "  💡 나중에 전환하려면: setup.sh 재실행 또는 .env에서 DRY_RUN=false"
fi

# ── 12. 완료 ──
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🎉 설치 완료!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  실행:   ./start.sh"
echo "  모드:   DRY_RUN=$DRY_RUN"
echo ""
